#pragma once

#include <vector>

#include "CL_CAD.h"
#include "Articles.h"
#include "Client.h"
#include "Personnel.h"
#include "Commande.h"
#include "CL_Com_mapping.h"
#include "CL_Svc_gestion.h"
#include "mappingClient.h"
#include "gestionClient.h"
#include "mappingPersonnel.h"
#include "gestionPersonnel.h"
#include "mappingArticles.h"
#include "gestionArticles.h"
#include "mappingCommandes.h"
#include "gestionCommandes.h"
#include "gestionPersonnelFormulaire1.h"
#include "GestionClientFormulaire.h"
#include "gestionCommandeFormulaire.h"
#include "gestionArticlesFormulaire.h"
#include "gestionStatFormulaire.h"
#include "ajouterArticle.h"
#include "supprimerArticle.h"
#include "MainFormulaire1.h"